site_name: st-paywall
site_url: https://github.com/tylerjrichards/st-paywall
theme: readthedocs
markdown_extensions:
  - toc:
      baselevel: 2
nav:
  - Home: index.md
  - Authentication: authentication.md
  - "Subscription with Stripe": subscription-stripe.md
  - "Subscription with Buy Me A Coffee": subscription-buymeacoffee.md
  - "Contribute": contribute.md 